server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/dbAuth
    username: usr
    password: pwd
  flyway:
    enabled: true

  security:
    oauth2:
      authorizationserver:
        client:
          public-client:
            registration:
              client-id: "public-client"
              client-authentication-methods:
                - "none"
              authorization-grant-types:
                - "authorization_code"
              redirect-uris:
                - "http://127.0.0.1:3000/callback"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true
            require-proof-key: true
            token:
              access-token-time-to-live: 3600000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
